# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
# cannot extract pack cache, as it's using a named volume

# variables:
#   ArtifactFeed: 6ebc2d9e-a94e-416e-b463-fea4fdb4ffb8

trigger:
  - Azure

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    ls -al
- script: |
    echo Starting the build
    mvn clean package -DskipTests
  displayName: 'Build with Maven'
- publish: $(System.DefaultWorkingDirectory)/account-service
  artifact: account-service
- publish: $(System.DefaultWorkingDirectory)/auth-service
  artifact: auth-service
- publish: $(System.DefaultWorkingDirectory)/gateway
  artifact: gateway
  
# steps:
#   - script: |
#       ls -al
#   - script: |
#       mvn clean package -DskipTests
#   - script: |
#       ls -al
#   - script: |
#       artifacts:
#         - from: 'account-service'
#           to: 'account-service'
#           include: 
#             - 'target\**\*'

#   - script: |
#       docker login -u normanch -p "${pswd}"
#     env:
#       pswd: $(dockerPassword)
#   - script: |
#       cd ./account-service
#       ls -al
#       docker build -t normanch/piggymetrics-account-service .
#   - script: |
#       cd ./auth-service
#       ls -al
#       docker build -t normanch/piggymetrics-auth-service .
#   - script: |
#       cd ./gateway
#       ls -al
#       docker build -t normanch/piggymetrics-gateway .
#   - script: |
#       cd ./notification-service
#       ls -al
#       docker build -t normanch/piggymetrics-notification-service .
#   - script: |
#       cd ./statistics-service
#       ls -al
#       docker build -t normanch/piggymetrics-statistics-service .
#   - script: |
#       docker push normanch/piggymetrics-account-service:latest
#       docker push normanch/piggymetrics-auth-service:latest
#       docker push normanch/piggymetrics-gateway:latest
#       docker push normanch/piggymetrics-notification-service:latest
#       docker push normanch/piggymetrics-statistics-service:latest
#   - script: |
#       docker images